---
version: 2.1

executors:
  python3:
    docker:
      - image: cimg/python:3.11
    resource_class: small
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    executor: python3
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: circleci-mamono210-aws-lambda-pdf
          session-duration: '2100'
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python common_modules/pdf_pager/tests/pdf_pager_test.py
            python tests/test_1.py
            python tests/test_2.py
      - store_artifacts:
          path: artifacts/
          destination: test_artifacts
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace

workflows:
  version: 2.1
  builds:
    jobs:
      - trailing-whitespace
      - build:
          context: aws-oidc
          requires:
            - trailing-whitespace
